defaultSeverity: error
ignoreFiles: ['/**/*min.scss']
plugins:
    - stylelint-scss
extends:
    - stylelint-config-standard-scss
    - stylelint-config-prettier
rules:
    # Formatting
    # value-list-comma-space-after: 'always'
    # function-comma-space-after: 'always'
    # media-query-list-comma-space-after: 'always'
    # block-closing-brace-space-before: 'always-single-line'
    # block-opening-brace-space-before: 'always'
    # declaration-colon-space-before: 'never'
    # declaration-colon-space-after: 'always'
    # function-parentheses-space-inside: 'never'
    # function-calc-no-unspaced-operator: true
    # declaration-block-trailing-semicolon: 'always'
    # indentation: 'tab'

    import-notation: 'string'
    selector-class-pattern: null
    value-keyword-case: null
    scss/dollar-variable-pattern: null
    scss/at-mixin-pattern: null
    font-family-name-quotes: "always-where-recommended"
